apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webapp-data
  namespace: webapp
  labels:
    app: webapp
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 1Gi
